easy_admin:
    site_name: '<img src="/img/logo_1office_GB_H.svg" width="150" height="50" alt="1Office">'
    formats:
        date: 'Y-m-d'
        datetime: 'Y-m-d H:i'
    design:
        brand_color: '#98c93c'
        assets:
            css:
                - 'css/admin.css'
            favicon:
                path: '/img/Favicon_-_1Office.png'
                mime_type: 'image/png'
        menu:
            - { entity: 'SyncRecord', default: true }
            - User
#        templates:
#            field_boolean: ''
    entities:
        User:
            class: App\Entity\User
            label: Users
            form:
                fields:
                    - username
                    - usernameCanonical
                    - email
                    - emailCanonical
                    - enabled
#                    - groups
                    - roles
            list:
                fields: ['id', 'username', 'email', 'enabled', 'lastLogin']

        SyncRecord:
            class: App\Entity\SyncRecord
            label: 'Synchronization records'
            form:
                fields:
                    - { type: 'section', columns: 12, label: 'General'}
                    - name
                    - active
                    - { type: 'section', columns: 6, label: 'Smart accounts API'}
                    - smartAccountsApiKeyPublic
                    - smartAccountsApiKeyPrivate
                    - { type: 'section', columns: 6, label: 'TransferWise API'}
                    - transferWiseApiToken
            list:
                fields: ['id', 'name', 'active', 'created', 'updated']
            search:
                fields: ['id', 'name']
            new:
                fields: ['name', 'smartAccountsApiKeyPublic', 'smartAccountsApiKeyPrivate', 'transferWiseApiToken', 'active']
            edit:
                fields: ['name', 'smartAccountsApiKeyPublic', 'smartAccountsApiKeyPrivate', 'transferWiseApiToken', 'active']
